blank_issues_enabled: false
contact_links:
  - name: Contribution Guidelines
    url: https://github.com/dhruv0206/opensource-issues-finder/blob/master/CONTRIBUTING.md
    about: Check the contribution guidelines for common questions
